//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_surname { get; set; }
        public string customer_phone { get; set; }
        public string customer_adress { get; set; }
        public string customer_mail { get; set; }
    }
}
