//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int task_id { get; set; }
        public int customer_id { get; set; }
        public int users_user_id { get; set; }
        public string task_product_type { get; set; }
        public string task_product_name { get; set; }
        public string task_product_brand { get; set; }
        public string task_product_serial_number { get; set; }
        public string task_detail { get; set; }
        public Nullable<int> task_status { get; set; }
    }
}
