//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Desk.ServiceDesk_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/Sd_service")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable CustomersTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable CustomersTable {
            get {
                return this.CustomersTableField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersTableField, value) != true)) {
                    this.CustomersTableField = value;
                    this.RaisePropertyChanged("CustomersTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/Sd_service")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskData", Namespace="http://schemas.datacontract.org/2004/07/Sd_service")]
    [System.SerializableAttribute()]
    public partial class TaskData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable TaskTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable TaskTable {
            get {
                return this.TaskTableField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTableField, value) != true)) {
                    this.TaskTableField = value;
                    this.RaisePropertyChanged("TaskTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDesk_service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        int login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_customer", ReplyAction="http://tempuri.org/IService1/create_customerResponse")]
        int create_customer(string customer_name, string customer_surname, string customer_phone, string customer_mail, string customer_adress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/customer", ReplyAction="http://tempuri.org/IService1/customerResponse")]
        Service_Desk.ServiceDesk_service.CustomerData customer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/user", ReplyAction="http://tempuri.org/IService1/userResponse")]
        Service_Desk.ServiceDesk_service.UserData user();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/task", ReplyAction="http://tempuri.org/IService1/taskResponse")]
        Service_Desk.ServiceDesk_service.TaskData task();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create_task", ReplyAction="http://tempuri.org/IService1/create_taskResponse")]
        int create_task(int customer_id, int users_user_id, string task_product_type, string task_product_name, string task_product_brand, string task_product_serial_number, string task_detail, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/update_task", ReplyAction="http://tempuri.org/IService1/update_taskResponse")]
        int update_task(int task_id, int status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Service_Desk.ServiceDesk_service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Service_Desk.ServiceDesk_service.IService1>, Service_Desk.ServiceDesk_service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public int create_customer(string customer_name, string customer_surname, string customer_phone, string customer_mail, string customer_adress) {
            return base.Channel.create_customer(customer_name, customer_surname, customer_phone, customer_mail, customer_adress);
        }
        
        public Service_Desk.ServiceDesk_service.CustomerData customer() {
            return base.Channel.customer();
        }
        
        public Service_Desk.ServiceDesk_service.UserData user() {
            return base.Channel.user();
        }
        
        public Service_Desk.ServiceDesk_service.TaskData task() {
            return base.Channel.task();
        }
        
        public int create_task(int customer_id, int users_user_id, string task_product_type, string task_product_name, string task_product_brand, string task_product_serial_number, string task_detail, int status) {
            return base.Channel.create_task(customer_id, users_user_id, task_product_type, task_product_name, task_product_brand, task_product_serial_number, task_detail, status);
        }
        
        public int update_task(int task_id, int status) {
            return base.Channel.update_task(task_id, status);
        }
    }
}
